version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.0.0

jobs:
  say-hello:
    docker:
      - image: cimg/aws:2023.06
    steps:
      - checkout
      - aws-cli/setup:
          role_arn: ${AWS_ROLE_ARN}
          region: ${AWS_REGION}
          profile_name: "CircleCI"
          role_session_name: "CircleCI project OIDC"
          session_duration: "900"
      - run:
          name: "Test AWS OIDC authentication"
          command: |
            aws sts get-caller-identity --profile "CircleCI"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
