version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.0.0
  terraform: circleci/terraform@3.2.1

jobs:
  deployment:
    executor:
      name: terraform/default
      tag: 1.4.6
    steps:
      - checkout
      - aws-cli/setup:
          role_arn: ${AWS_ROLE_ARN}
          region: ${AWS_REGION}
          profile_name: CircleCI
          role_session_name: CircleCI_project_OIDC
          session_duration: "900"
      - run:
          name: "Test AWS OIDC authentication"
          command: |
            aws sts get-caller-identity --profile "CircleCI"
      - run:
          name: "Test terraform version"
          command: |
            terraform version
      - terraform/init:
          backend_config: bucket=${S3_BACKEND_BUCKET},key=${S3_BACKEND_KEY},profile=CircleCI
      - terraform/fmt
      - terraform/validate
      - terraform/plan
      - when:
          condition:
            equal: [ main, << pipeline.git.branch >> ]
          steps:
            - terraform/apply


workflows:
  deployment-workflow:
    jobs:
      - deployment
